repos:
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: ^(.git|__pycache__|docs/source/conf.py|old|build|dist|tests|whisper)
    args:
      - --max-complexity=10
      - --max-line-length=127
      - --select=E9,F63,F7,F82
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    types: [python]
    exclude: ^(whisper|docs/)
    args:
      - -S
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    args:
      - -S